### ISSUE TITLE
Better error handling for invalid schemas

### ISSUE THREAD

**Issue by marklawlor** [piglovesyou/graphql-let#101]
Not sure if this is an issue with graphql-let or @graphql-codegen, but if you have an error with your schema, the only error message is `[ graphql-let ] Failed to load schema`. Is there a way a more detailed error that could be exposed? (eg line number of the error)

**Comment by piglovesyou** [comment]
<details><summary>I see this in my local env when I intentionally break schema content and run graphql-let command.</summary>
<pre><code>```
[ graphql-let ] Running graphql-codegen...
[ graphql-let ] Failed to load schemaError: Failed to load schema
    at loadSchema (/Users/soichitakamura/tmp/with-typescript-graphql-app9/node_modules/@graphql-codegen/cli/index.cjs.js:336:15)
    at async generateSchema (/Users/soichitakamura/tmp/with-typescript-graphql-app9/node_modules/graphql-let/dist/lib/create-codegen-opts.js:31:26)
    at async Object.createCodegenOpts [as default] (/Users/soichitakamura/tmp/with-typescript-graphql-app9/node_modules/graphql-let/dist/lib/create-codegen-opts.js:41:17)
    at async prepareFullGenerate (/Users/soichitakamura/tmp/with-typescript-graphql-app9/node_modules/graphql-let/dist/lib/full-generate.js:83:25)
    at async Object.fullGenerate [as default] (/Users/soichitakamura/tmp/with-typescript-graphql-app9/node_modules/graphql-let/dist/lib/full-generate.js:107:42)
    at async gen (/Users/soichitakamura/tmp/with-typescript-graphql-app9/node_modules/graphql-let/dist/gen.js:14:28)
```
</code></pre>
</details>

* Can I get your graphql-let version? The latest is v0.10.0.
* Can you trace when/which error causes the output?

**Comment by marklawlor** [comment]
Running v0.10.0

My **invalid** schema.d.ts 

```
type Query {
  test: string
}
```

graphql-let gives me the error:

`[ graphql-let ] Failed to load schemaError: Failed to load schema`

Testing with other GraphQL tools (ApolloServer and graphql-tag) both give the error 

`Error: Unknown type "string". Did you mean "String"?`

While developing with `graphql-let` I'm finding myself constantly copying my schema into other tools just to get a more meaningful error message. It would be extremely useful if `graphql-let` had similar error messages.

**Comment by salzhrani** [comment]
this should be fixed in v0.10.1, can you please check?

**Comment by piglovesyou** [comment]
@marklawlor , Mr. @salzhrani solved this problem. Would you mind to take a look if you see a better error message? Please reopen it if you don't.

**Comment by marklawlor** [comment]
@piglovesyou @salzhrani The use case I specified above is not solved with version v0.11.1, I still receive the exact same output when graphql-let is loading my schema.

However I am getting much better error messages for my documents, so thank you for that.

**Comment by marklawlor** [comment]
For reference my `.graphql-let.yaml` is 

```
schema: "schema.graphqls"
documents: "**/*.graphql"
respectGitIgnore: true
plugins:
  - typescript
  - typescript-operations
  - typescript-react-apollo
```

And my **invalid** schema.graphqls is

```
type Query {
  test: string
}
```

**Comment by salzhrani** [comment]
I think this might get better soon

**Comment by piglovesyou** [comment]
You're right @marklawlor, I missed `err.details` in what Listr generates. From v0.15.3, [this kind of message](https://github.com/piglovesyou/graphql-let/blob/6970d46379e69dc07c77e4764805a3366d29034c/test/gen.test.ts#L80-L84) should appear.
