### ISSUE TITLE
Output directory?

### ISSUE THREAD

**Issue by james-ff** [piglovesyou/graphql-let#109]
Is there a config option available to specify an output directory of all .graphql.d.ts files?
- Would make clearing out these generated files easier for clean scripts and before a new run
- old generated files currently remain after a graphql file is renamed between runs

**Comment by piglovesyou** [comment]
Thank you for creating the issue, that's a good point.

* Maybe we should get `generateDir` back to our config for those who want to control it.
* Besides, graphql-let command line can erase old outputs on execution, the size will continue to increase otherwise.

**Comment by piglovesyou** [comment]
v0.11.1 solves this issue.

**Comment by james-ff** [comment]
How do the imports work now that the generated files are in a subdirectory of node_modules?

**Comment by piglovesyou** [comment]
@james-ff Sorry, I got confused, your point is to put all `*.graphql.d.ts` into the custom directory. Let me rethink to support it.

**Comment by piglovesyou** [comment]
@james-ff  Previously graphql-let generates `__generated__/types/*.graphql.d.ts` but [the issue came up](https://github.com/piglovesyou/graphql-let/issues/82). I would like to ask you what output (`.d.ts`) you would expect if the two files below are in your source directory?
* ./mutations/Device.graphql
* ./queries/Device.graphql

**Comment by james-ff** [comment]
I currently have a temporary two step process in place with "graphql-codegen":
1. Generate a `documents.ts` file containing the contents of all .graphql files wrapped with `gql` and exported in ts
- using plugin 'typescript-document-nodes'
2. Generate a `types.ts` file containing typescript types, derrived from the exports in `documents.ts`:
- using plugins 'typescript' & 'typescript-operations'

I keep all .graphql files in my frontend repo within `/graph/{queries/mutations}`
And all generated files in `/graph/generated/{filename}`

Ideally, all this would be done with `graphql-let` and I would have one `something.d.ts` file to work with
- like: `import { Query, QueryVariables, etc } from 'graph/generated/types.d.ts'` or similar

**Comment by piglovesyou** [comment]
I see, so you're trying to gather multiple .graphql files and create a single .d.ts for them.

* I think that's the different demand from what this issue initially states. I can't imagine if graphql-let does that, but how about creating another issue?
* Generating .graphql.d.ts to the custom dir [had a problem](https://github.com/piglovesyou/graphql-let/issues/82). Besides, it seems that's not what you'd like. I'd like to close this issuer now, where I solved one of your problems; "old generated files currently remain".

Thank you for taking the time to describe your situation. Please make another comment anytime.
