### ISSUE TITLE
typescript compiler custom config

### ISSUE THREAD

**Issue by salzhrani** [piglovesyou/graphql-let#112]
Hello,
I am facing an issue where my schema has a subscription and the generated tsx has `AsyncIterator` type.
for typescript to generate the declarations it requires the that the compiler lib option to be set to a target that can handle `AsyncIterator` like `esnext`.
Currently there is no API to override the compiler options [here](https://github.com/piglovesyou/graphql-let/blob/master/src/lib/dts.ts#L6).
in my case if `graphql-let` used my tsconfig.json, the files would have been properly generated.

**Comment by piglovesyou** [comment]
Hi @salzhrani, it definitely should respect the root tsconfig.json, while it doesn't as you know. This would be the impl plan:

* It should load the root tsconfig.json by default
* Customizing path to tsconfig.json in .graphql-let.yml would also be nice

**Comment by salzhrani** [comment]
I am working on a PR right now.
one concern I have is that loading tsconfig.json by default might break the generation for some users, we can either make it disabled by default or make it the new default if you prefer

**Comment by piglovesyou** [comment]
@salzhrani Cool, exactly. I would say, let's make it default. I've taken care of breaking changes but this one sounds a bug, where most people will expect graphql-let to respect tsconfig.json by default. I'll write a "Be careful" note on the release page, so I would like you to solve it if you agree.

**Comment by salzhrani** [comment]
Cool
