### ISSUE TITLE
use @graphql-codegen/cli instead of @graphql-codegen/core

### ISSUE THREAD

**Issue by salzhrani** [piglovesyou/graphql-let#117]
as per [the documentation](https://github.com/dotansimha/graphql-code-generator/blob/6e045885d1ca66d69ce1ac069380b5c75cc5a91e/website/docs/getting-started/programmatic-usage.md) we can use cli instead and benefit from more feature parity with graphql-codegen. do you think it is a good idea?

**Comment by piglovesyou** [comment]
@salzhrani Yeah we should do that, but I remember once I tried it I needed some of functions in @graphql-codegen. Could you take a look? I'm 100% agree to use a smaller package.
