### ISSUE TITLE
Export "graphql-let/jestTransformer" 

### ISSUE THREAD

**Issue by piglovesyou** [piglovesyou/graphql-let#123]
To let users have a graphql-let transformer in jest.config.json, configured as:

```js
module.exports = {
  transform: {
    '\\.(graphql|graphqls)$': 'graphql-let/jestTransformer',
  },
},
```

and let them run Jest tests with [@apollo/client/testing](https://www.apollographql.com/docs/react/development-testing/testing/#mockedprovider) as:

```js
import { MockedProvider } from "@apollo/client/testing";
import {readFileSync} from 'fs';
import renderer from 'react-test-renderer';

const mocks = [
  {
    request: {
      query: readFileSync('../lib/viewer.graphql', 'utf-8'),
      variables: { first: 4 }
    },
    result: {
      data: {
        dog: {
          name: "Douglas"
        }
      }
    }
  },
]

it("runs the mocked query", () => {
  const tree = renderer.create(
    <MockedProvider mocks={mocks}>
      <MyQueryComponent />
    </MockedProvider>
  ).toJSON()

  expect(tree).toMatchSnapshot();
});
```

**Implementation:** Jest transformer must be synchronous. We have to ask users to run graphql-let command beforehand and read the generated .tsx synchronously when the transformer is called. The way to integrate Babel is what I need to learn.

**Comment by irrelevelephant** [comment]
I submitted a PR for this [here](https://github.com/piglovesyou/graphql-let/pull/126).

**Comment by piglovesyou** [comment]
@irrelevelephant solved this problem! 🎉
