### ISSUE TITLE
Local state?

### ISSUE THREAD

**Issue by Maetes** [piglovesyou/graphql-let#124]
Hey,

it's less of an issue rather than a question and i really enjoyed to use graphql-let in one of my projects.

But how is it possible to use the abilitie of handling the local state with apollo? I mean it's not possible anymore to write gql`` with @client directive? Am I missing something or does the use of graphql-let disable apollo`s local state handling?

(not a big issue but would love to learn if it's possible to still rely on it).

Thanks (:

**Comment by piglovesyou** [comment]
Hi @Maetes. Did you try `@client` directive in your `query.graphql`? graphql-let doesn't disable it and is supposed to have nothing to do with it. Do you get any log?

**Comment by Maetes** [comment]
Hi @piglovesyou sorry for the late response. I didn't try because the project has to be rolled out in a tough deadline so i opt for the conext based local state management.

You are of course right i totally forgot about this option and was only focused on the gql tag option ones. Since apollo client now introduced the reactive variables all the local statemanagement is totally reasonable to push to apollo client by now. Before that i was in conflict with myself because this local resolver thing is im my eyes to complicated compared to context based local state management.

Thanks anyway!!!

**Comment by piglovesyou** [comment]
No problem at all. Yeah, Reactive variables is awesome, maybe we can forget "@client" directive from the next project.

**Comment by Maetes** [comment]
> No problem at all. Yeah, Reactive variables is awesome, maybe we can forget "@client" directive from the next project.

I think so, yes. I mean if you want you still can use a @client in your query after defining the read function in the typePolicies cache but sticking to only use this simple cool variables only approach is really nice.
