### ISSUE TITLE
Support Typed Document Node

### ISSUE THREAD

**Issue by NickClark** [piglovesyou/graphql-let#127]
Would be nice if this could support `graphql-typed-document-node`

I've added the issue to both projects since at this point I don't know which library should be the one to handle this.

Generates the following error:

```
Plugin "typed-document-node" validation failed:


 Found 1 error

  ✖  <redacted>/node_modules/graphql-let/__generated__/src/renderer/auth/graphql/documents.graphql.tsx
    Plugin "typed-document-node" requires extension to be ".ts"!
    Error: Plugin "typed-document-node" validation failed:
        at executePlugin (<redacted>/node_modules/@graphql-codegen/core/index.cjs.js:31:19)
    Error: Plugin "typed-document-node" validation failed:
        at executePlugin (<redacted>/node_modules/@graphql-codegen/core/index.cjs.js:31:19)

```

**Comment by piglovesyou** [comment]
Hi. Can I ask what do you expect in your code? Not sure but if you want types for generated code, that's what graphql-let originally do so the plugin might not be necessary.

**Comment by NickClark** [comment]
This makes it so when using libraries like Apollo, just using the imported Document Node with the library's API, you get correctly typed results. No need for verbose calls where you have to set all the right generic types.

**Comment by NickClark** [comment]
Currently seems this will be taken care of on the plugin side. Closing for now.
