### ISSUE TITLE
Jest Next Exampl

### ISSUE THREAD

**Issue by alexwine36** [piglovesyou/graphql-let#143]
Is there an example that exists for a usable configuration with Next, graphql-let, and Jest

I have been trying to get the configuration to work using the graphql-let/jestTransformer but the closes I get is that __generated__ file doesn't exist.

**Comment by piglovesyou** [comment]
Hi! Does [this](https://github.com/piglovesyou/nextjs-example-typescript-jest) help? I'll improve the docs later.

**Comment by alexwine36** [comment]
It did indeed the other portion that ended up clinching it was adding cacheDir to the graphql-let configuration file

Thanks for the help

**Comment by piglovesyou** [comment]
I made [PR](https://github.com/vercel/next.js/pull/16101) to them.
