### ISSUE TITLE
not importing hook

### ISSUE THREAD

**Issue by traviseden** [piglovesyou/graphql-let#145]
I tried to clone and run the Next.js example as suggested:

```
yarn create next-app --example with-typescript-graphql with-typescript-graphql-app
yarn
yarn dev
```

Visiting the home page in my browser gives the following error:

```
event - build page: /
wait  - compiling...
error - ./pages/index.tsx
Attempted import error: 'useViewerQuery' is not imported from '../lib/viewer.graphql'.
```

The ViewerDocument works fine with graphql. It also exports ViewerComponent which works and withViewer which I did not try. But no useViewerQuery hook. Here is what is imported:

```
Object [Module] {
  ViewerDocument: [Getter],
  ViewerComponent: [Getter],
  withViewer: [Getter]
}
```

**Comment by piglovesyou** [comment]
Hi, sorry for the inconvenience. Could you update all the deps starting with `@graphql-codegen/*`? `@graphql-codegen/typescript-react-apollo` of v1 and v2 switches the default value of `withHooks` and `withHooks: true`, and graphql-let removed the configuration modification recently. I'm [requesting the fix](https://github.com/vercel/next.js/pull/16101).

**Comment by guillaumeLamanda** [comment]
I had the same issue, thank's for the solution described here!  
It solves the issue for me. I bumped Apollo Client to v3 at the same time. 👌 
Thank's for your work on `graphql-let`, I love it 🙏

**Comment by piglovesyou** [comment]
So `yarn create next-app --example with-typescript-graphql` should work now. Could you try? Thanks.

**Comment by piglovesyou** [comment]
Please open it if there's trouble.
