### ISSUE TITLE
respectGitIgnore:false in yml config not working

### ISSUE THREAD

**Issue by ssypi** [piglovesyou/graphql-let#146]
I'm trying to use graphql schema and documents from library inside node_modules so I set respectGitIgnore: false inside .graphql-let.yml, but it doesn't work. It still ignores node_modules and cannot find any documents.

My findings:

Inside findTargetDocuments (graphql-let function) I put console.log to see what's inside the config and found out that:

1. If i set it to something else, it correctly shows the value in the console log, so this lets me know I put the config in right place.
2. If I set it to false, it still shows up as true, the false values is lost somewhere before this function. No documents found for generation because node_modules is ignored even though it shouldn't be.
3. If I manually change the function to ignore the config setting and always use false as gitignore, then everything works and documents are found.

My environment:
Windows 10
graphql-let version 0.15.0
nodejs version 14.7.0

**Comment by ssypi** [comment]
I think I found the problem:

https://github.com/piglovesyou/graphql-let/blob/3802ece0d9abd2dd7849ffea7648a4d44fae90af/src/lib/config.ts#L49

This line:
```respectGitIgnore: raw.respectGitIgnore || true,```

will evaluate to true even if respectGitIgnore is false.

**Comment by piglovesyou** [comment]
Hi, @ssypi. That is correct😅 Glad if you could take time to make a PR.

**Comment by piglovesyou** [comment]
Thank you for your effort @ssypi. v0.15.2 includes your change.
