### ISSUE TITLE
Next.js example error "useViewerQuery" not exported from "../lib/viewer.graphql"

### ISSUE THREAD

**Issue by maxosen** [piglovesyou/graphql-let#160]
Following the NextJS example on the [README](https://github.com/zeit/next.js/blob/canary/examples/with-typescript-graphql/README.md#readme), I run into the following error:

"useViewerQuery" not exported from "../lib/viewer.graphql"
![image](https://user-images.githubusercontent.com/24519631/91539574-21148280-e94c-11ea-901f-3cd3afa7cf90.png)

### Steps to reproduce the error
1. Clone the https://github.com/zeit/next.js/blob/canary/examples/with-typescript-graphql/ Next.js example
2. Run `npm install`
3. Run `npm run dev`
4. Navigate to `localhost:3000`
5. Error

### Development Environment
Error reproducible on this Codesandbox: https://codesandbox.io/s/little-breeze-0yiye

I haven't try using graphql-let on Webpack, so I think the problem might be in the example itself. Or did I miss any step in the setup? Would appreciate it if anyone could help me out.

**Comment by piglovesyou** [comment]
Hi @maxosen , thanks for reporting. I'm requesting [a fix](https://github.com/vercel/next.js/pull/16101) so appreciate for a bit more patience.

**Comment by maxosen** [comment]
I appreciate the quick response. Just noticed the fix. I will close this issue once it's merged. Thanks for your work a lot!
