### ISSUE TITLE
Feature request: Inline GraphQL via webpack loader

### ISSUE THREAD

**Issue by marklawlor** [piglovesyou/graphql-let#169]
Opening this issue for voting as per the README.

I came across this library [@graphql-tools/graphql-tag-pluck](https://www.npmjs.com/package/@graphql-tools/graphql-tag-pluck) which allows you to extract the `gql` template tags and treat the output as if it was a `.graphql` file. I'm assuming that would help with the implementation.

**Comment by piglovesyou** [comment]
Thank you @marklawlor for voting! Actually, I've tried it and [been stuck in the middle](https://github.com/piglovesyou/graphql-let/blob/handle-inline-by-loader/literal-loader.js). I'm working on the different project now so I can't promise I finish it soon. Please don't hesitate to make a PR. > all

**Comment by piglovesyou** [comment]
Please try [v0.17.0](https://github.com/piglovesyou/graphql-let/releases/tag/v0.17.0)🪐
