### ISSUE TITLE
Is there a way to combine multiple graphqls files into a single entry point?

### ISSUE THREAD

**Issue by SelvinM** [piglovesyou/graphql-let#211]
My  schema is getting big and hard to maintain. I would like to divide it into multiple files while still having the advantages of using .graphqls extension to define the schema. Is that possible?

**Comment by SelvinM** [comment]
Nevermind. I found the solution. Sorry!

**Comment by piglovesyou** [comment]
Hi @SelvinM. No problem.

This syntax will bind multiple schemas and provide an entry point to get ResolverTypes. > The future visitors
```yaml
schema: "**/*.graphqls"
schemaEntrypoint: schema.graphqls
```
