### ISSUE TITLE
.d.ts files are generated "too late"?

### ISSUE THREAD

**Issue by hasparus** [piglovesyou/graphql-let#243]
I build an app with Nx and webpack. `.graphql.d.ts` files are generated, but the typecheck fails. I encountered a similar problem writing a test here, but I'm not sure what's wrong.

**Comment by piglovesyou** [comment]
Hi @hasparus, that's severe. I'll check it later, hopefully in this weekend.

**Comment by hasparus** [comment]
I think I encountered another side of this problem.

I'm using graphql-let with Next.js, and it seems I need a codegen step before build.
I'm getting an error on import before loaders run.

```
Type error: Cannot find module 'src/path/query.graphql' or its corresponding type declarations.
```

**Comment by piglovesyou** [comment]
Hmm,[ it awaits on writing files](https://github.com/piglovesyou/graphql-let/blob/3260263bcc84e0e1885661fc24a3d7353081a3dd/src/lib/dts.ts#L141). But I think tests of type checking lack. It's helpful if there's a reproduction project.

**Comment by piglovesyou** [comment]
[I wrote a lot of tests running `tsc` after code generation](https://github.com/piglovesyou/graphql-let/blob/051e5987131e0384575080ad02a0478eb777fb20/src/gen.test.ts#L17-L22). I'd like you to try again. Please reopen this if you notice anything.
