### ISSUE TITLE
Can't install the package

### ISSUE THREAD

**Issue by mengqing** [piglovesyou/graphql-let#27]
Getting the following error, not sure why this is happening

```
Now using node v12.14.1 (npm v6.13.4)
➜  npm i --save graphql-let
npm ERR! Unexpected end of JSON input while parsing near '...MCPYrqEdsEE4APu0U9D5q'

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/xxx/.npm/_logs/2020-01-19T12_53_04_317Z-debug.log
```

**Comment by piglovesyou** [comment]
Hello. I couldn't reproduce it with the Node/NPM version. Would you mind:

* removing `node_modules` and running `npm install` again
* uninstalling the related packages and installing them again (suspecting something is wrong with package-lock.json)
* removing `package-lock.json` if it's okay
* pointing where the `...MCPYrqEdsEE4APu0U9D5q` is located 
* pasting the error log

**Comment by piglovesyou** [comment]
Tell me if you still have trouble.
