### ISSUE TITLE
What's the best way to integrate graphql-let to create-react-app?

### ISSUE THREAD

**Issue by blatoo** [piglovesyou/graphql-let#317]
Hi all,

I use `create-react-app` for my project, according the read me, I should modify the `webpack.config.ts` file. But I can not find it...

Should I create it? In project root `/` or source `/` ?

Thanks very much for the help!

Conny

**Comment by piglovesyou** [comment]
Hi. I think it's a good idea to refer to the [facebook/create-react-app](https://github.com/facebook/create-react-app) docs.

**Comment by blatoo** [comment]
> Hi. I think it's a good idea to refer to the [facebook/create-react-app](https://github.com/facebook/create-react-app) docs.

thanks for the suggestion. After read the doc, I figured it out that I should use `npm run eject` to edit the `webpack.config.ts`, however, after `eject`, you have to maintain all the settings and configurations by yourself:

> Ejecting lets you customize anything, but from that point on you have to maintain the configuration and scripts yourself. This can be daunting if you have many similar projects. In such cases instead of ejecting we recommend to fork react-scripts and any other packages you need. This article covers how to do it in depth. You can find more discussion in this issue.

So, the recommended way to avoid the `npm run eject` is write your own `react-scripts`. I am a beginner, I am not sure, whether my understanding of this part is correct. 

By the way, @piglovesyou  your name is very lovely.  😄

**Comment by piglovesyou** [comment]
Thanks for describing the result. I think this issue can guide the best way to integrate graphql-let to create-react-app. Let me please change the title and reopen.

**Comment by zimme** [comment]
Another option is to use craco to setup graphql-let, however in doing so I had some trouble getting the babel loader to work. Will post back if we can enable the babel loader too.

**Comment by MrEmanuel** [comment]
I'm also trying to figure out how to add `graphql-let` to my `create-react-app` project. 
It looks like [craco](https://www.npmjs.com/package/@craco/craco) might be the best option. 

It lets you override `create-react-app` config and, for instance add a custom loader to webpack, or change the typescript compiler. 

I found craco via [this blog](https://blog.johnnyreilly.com/2021/01/create-react-app-with-ts-loader-and-craco.html) post which was a good read.

**Comment by piglovesyou** [comment]
CRACO seems great to keep an app scaling! Currently, I'm preparing 0.17.0 to support babel-plugin-macro, which [create-react-app supports out of the box without configuration](https://github.com/kentcdodds/babel-plugin-macros/blob/main/other/docs/user.md#using-with-create-react-app). I assume this would be the way for now. I'll let you guys know when it's ready.

```typescript jsx
import { gql, load } from 'graphql-let/macro';

const { useViewer1Query } = gql(`
  query Viewer1 {
      viewer {
          id
          name
          status
      }
  }
`);
const { useViewer2Query } = load('./viewer2.graphql');
```

**Comment by piglovesyou** [comment]
Please try [v0.17.0](https://github.com/piglovesyou/graphql-let/releases/tag/v0.17.0)🪐
