### ISSUE TITLE
Usage with lint-staged

### ISSUE THREAD

**Issue by matheus-rosin** [piglovesyou/graphql-let#348]
Hi there!

I'm trying to build my TS application before committing, and for this purpose it is necessary to generate TS files for GraphQL schema.

Husky calls lint-staged, and lint-staged config file is as follows:

```json
{
  "./**/*.{js,jsx,ts,tsx,graphql,graphqls}": [
    "npm run lint",
    "graphql-let",
    "ENVIRONMENT=development next build --debug"
  ]
}
```

First command only calls eslint --fix, then we have graphql-let.
It fails with the following result:

```
[ graphql-let ] Usage: graphql-let [command]

graphql-let                   Generates .graphql.d.ts beside all GraphQL documents based on .graphql-let.yml config
graphql-let --config [FILE]   Generates .graphql.d.ts given a config file
graphql-let init              Generates a template of .graphql-let.yml configuration file 
```

It seems to be expecting one argument, but in this case, there is no one to pass.

I've already tried `graphql-let`, `yarn graphql-let` and `yarn run graphql-let`; also, created one script in package.json for that and called in lint-staged file, all with the same result.

Am I doing something wrong?

Thanks :)

**Comment by matheus-rosin** [comment]
Problem is with lint-staged; it seems that expects args to be passed, so using `yarn graphql-let gen` works fine.
Thanks anyway!

**Comment by piglovesyou** [comment]
Hello, belatedly. lint-staged passes these commands with filepath, so running `graphql-let xxx.ts` shows the command help.
