### ISSUE TITLE
Error when using babel plugin

### ISSUE THREAD

**Issue by mhaagens** [piglovesyou/graphql-let#373]
```
[ graphql-let ] [BABEL] unknown: Preset /* your preset */ requires a filename to be set when babel is called directly,
babel.transform(code, { filename: 'file.ts', presets: [/* your preset */] });
```

**Comment by piglovesyou** [comment]
Do you have any idea how I can reproduce it with which versions?

**Comment by piglovesyou** [comment]
I'm improving the base implementation including Babel. I think your case will solve too. Please be patient until v0.17.0 is released.

**Comment by piglovesyou** [comment]
@mhaagens Would you mind trying again with v0.17.0? I wrote stricter test cases in it.

**Comment by piglovesyou** [comment]
I'd like you to reopen it with steps to reproduce if you still have the errors.
