### ISSUE TITLE
[0.18.x] generated `.tsx` files imports `__types__.tsx` from a wrong path

### ISSUE THREAD

**Issue by guillaumeLamanda** [piglovesyou/graphql-let#449]
Hi here, 

I use graphql-let (an awesome tool by the way!) on an open-source project. 
The 0.17 version broke the Typescript Type Checking. The error says : 

`Type error: 'typeDefs' only refers to a type, but is being used as a value here.`

I import the schema for a graphql server.

Here is the PR opened by dependabot. 
https://github.com/guillaumeLamanda/twitter-follow2list/pull/109

I read the changelog of the 0.17, but I am not sure if I'm concerned by the changes needed.

This project use NextJS 10.1

**Comment by piglovesyou** [comment]
Hi @guillaumeLamanda. It seems "Vercel — Deployment has failed," but I can't see the detail build log. It's 404, maybe because of an authentication problem. Could you paste it here?

**Comment by guillaumeLamanda** [comment]
Hi @piglovesyou, and sorry for the delay. 
I have seen you released a newer version, so I tried to upgrade to fix the previous issue. 
I have some trouble upgrading, but the error leading to this issue is gone, so I will rename it. 

Here is my current issue :  

The generated files in the `.cache` folder do not point to the `__types__` files, as you can see [here]. I pushed the concerned folder to simplify the understanding. 

The path `"../../../../node_modules/@types/graphql-let/__generated__/__types__";` should be `"../../../../__types__"`.  
Maybe I missed a configuration here? 

Also, before I was able to import the schema types by directly importing from the schema file. In this version, I didn't see any file for types definitions created for the schema. It seems to be [intended](https://github.com/piglovesyou/graphql-let#no-preset). [So I need to import the corresponding type from the `.cache/__types__.tsx` file](https://github.com/guillaumeLamanda/twitter-follow2list/pull/109/files#diff-ff2e8b1977626606ceee943cbcc440a09390b1fba00d6ee5492dc63962f97f0d), which makes me feel "unsafe".  

Thanks for your time, and I am available if I can help here. 👍

**Comment by guillaumeLamanda** [comment]
Ok, it seems to work, thanks to you for the quick reply! 
Indeed, the migration is not easy, but I'm sure this issue will help future developers 😉  So I will describe the steps I have followed to make it work : 

1. Delete the `__generated__` folder, and all type definitions from graphql-let
```sh
rm -rf __generated__
rm **/*.graphql{,s}.d.ts
```
2. Update the `cacheDir` option from `.graphql-let.yml` from `__generated__` to `.cache`
3. Remove the `typescript` plugin from graphql-let configuration
4. Exclude `.cache` folder from `.tsconfig` 

The deployment of my project is currently broken, but I can finally compile successfully with the last version of graphql-let. 

Concerning the import from `__types__.tsx` instead of my schema, I think it could be a nice to have. It will make me feel more confident about the type I'm dealing with 😁

**Comment by piglovesyou** [comment]
Thank you for the guide! [The v0.18.0 release note](https://github.com/piglovesyou/graphql-let/releases/tag/v0.18.0) also has a migration guide, happy if you take a look.

**Comment by guillaumeLamanda** [comment]
I totally missed it, my bad! It seems perfect 👍
