### ISSUE TITLE
Cached files not resolving node_modules correctly

### ISSUE THREAD

**Issue by ananta** [piglovesyou/graphql-let#481]
## Problem: 

Cached generated *.graphql.tsx files are'nt able to resolve the `node_moduels`.
![Screen Shot 2021-05-13 at 11 12 05 AM](https://user-images.githubusercontent.com/12180395/118082139-5ed31180-b3dc-11eb-9be0-2d1b7fe51da9.png)

## Expected:
Should be one up the directory
![Screen Shot 2021-05-13 at 11 16 59 AM](https://user-images.githubusercontent.com/12180395/118082356-c1c4a880-b3dc-11eb-9060-53dca190c05f.png)

Can anyone help me fix the issue. If I don't mention the cacheDirectory, it works perfectly. But I want to include it.

**Comment by piglovesyou** [comment]
Sorry for inconvenience. For now, please try v0.17.x. Thanks

**Comment by ananta** [comment]
@piglovesyou Gotach. I was using beta version XD. My bad. Thanks for your time!
