### ISSUE TITLE
Local-only fields Error

### ISSUE THREAD

**Issue by Acring** [piglovesyou/graphql-let#543]
Hi,

I want to use Local-only fields in my query graphql

- user.graphql
```
query getUsers{
  users{
    id
    name
    status
  }
  currentUser @client
}
```

But when i run ` yarn graphql-let`error comes 

`Error: Unable to find field "currentUser" on type "Query"!`

What is right way to write a Local-only fields in graph file with graphql-let

Thanks!!

**Comment by piglovesyou** [comment]
I think you can refer to [this page](https://www.graphql-code-generator.com/docs/integrations/apollo-local-state). Please reopen this if it doesn't help. Thanks for using graphql-let!
