### ISSUE TITLE
Config options not passed to grapqhl-code-generator

### ISSUE THREAD

**Issue by lukasluecke** [piglovesyou/graphql-let#57]
I'm running into this issue https://github.com/dotansimha/graphql-code-generator/issues/1133 with the generated resolver types. I have tried adding the `useIndexSignature: true` config entry, but to no avail 😕

**Comment by lukasluecke** [comment]
Seems like other config options aren't applied correctly either, e.g. `withComponent: false` still generates types that depend on `@apollo/react-components` - which I do not want to use in my project.

**Comment by piglovesyou** [comment]
Thank you for creating the issue and the PR! Tomorrow I’ll take time to look in deep.
