### ISSUE TITLE
Can't get resolver-types to work

### ISSUE THREAD

**Issue by lukasluecke** [piglovesyou/graphql-let#59]
First issue is that the types aren't "linked" to the GraphQL-Schema file as expected (i.e. no `declare module '*/schema.graphqls'`).

The second issue is that there seems to be a mismatch between what's generated in the `__concatedschema__.tsx` and what Apollo expects for `makeExecutableSchema`:
> Type 'undefined' is not assignable to type '(() => any) | GraphQLScalarType | IEnumResolver | IResolverObject<any, GraphQLResolveInfo, any> | IResolverOptions<...>'.  Interfaces.d.ts(86, 5): 
> The expected type comes from property 'resolvers' which is declared here on type 'IExecutableSchemaDefinition<GraphQLResolveInfo>'

**Comment by lukasluecke** [comment]
@piglovesyou Just a quick note on why I'm opening all these issues - I'm working on a talk about GraphQL code generation right now that's due in two weeks and was looking to use this library instead of just `graphql-code-generator`, due to the improved ergonomics. It would be awesome if it would work as expected by then, however there's no pressure - I can always just fall back to regular graphql-code-generator 🙂 Also if you need help on any of these issues just let me know!

**Comment by piglovesyou** [comment]
Thank you for the issues. You're actually improving this project (and hopefully this project contributes to the GraphQL community).

1. What would you like to achieve by "linking" them?
    * "Jump to declaration" in IDE? If then, it's similar to #25 (as you already know)
    * I don't think graphql-let can improve the "jumping" behavior for now, because IDEs are not sure how to link modules caring TypeScript import/webpack Loader import.
    * Specifying `import "*.graphqls"` lets you jump to `__concatedschema__-hash.d.ts` but then HMR doesn't work. Hmm.
2. I think that's what you can ask to the graphql-codegen team. `@graphql-codegen/typescript-resolvers` only can suite/improve the result.
    * But I faced that too. Not sure if you like it, but I would suggest [this](https://github.com/zeit/next.js/pull/10637/files#diff-682d12e5f9468d1190b78c5c58a34533R1-R9).
    * I think resolver types should be declared by `graphql` so libraries can just follow.

**Comment by lukasluecke** [comment]
@piglovesyou Somehow after regenerating the types (deleting the `__generated__` folder) after the update to `0.8.1` the generated types seem to be fine now.

However I still can not get the following to work:
`import typeDefs from '../schema.graphqls'`

All I get is this:
`server/schema.ts:9:22 - error TS2307: Cannot find module '../schema.graphqls'.`

I'm not sure why, seeing as it's almost exactly what you have in the Next.js example 🤔

**Comment by piglovesyou** [comment]
@lukasluecke I guess you use `graphql-let/schema/loader` as well as `graphql-tag/loader`, don't you. `graphql-let/schema/loader` only takes care of its resolver types, not types for `graphql-tag/loader`. In the case, you need two definitions for `'*.graphqls'`: one by graphql-let and on by yourself. I hope it helps. [Next.js example](https://github.com/zeit/next.js/blob/canary/examples/with-typescript-graphql/next-env.d.ts#L4-L7)

```typescript
declare module '*.graphqls' {
  import { DocumentNode } from 'graphql'
  export default typeof DocumentNode
}
```

**Comment by piglovesyou** [comment]
[v0.10.0](https://github.com/piglovesyou/graphql-let/releases/tag/v0.10.0) rearchitects the way to generate `.d.ts`s, which don't have `declare module "*/x.graphql"` anymore. I think the problems we discuss in this issue disappear. I'd like you to try and give me feedback.
