### ISSUE TITLE
next.js example hot reloading bug

### ISSUE THREAD

**Issue by deanslamajr** [piglovesyou/graphql-let#64]
I love this loader! Great work!!

Unfortunately, I believe I've found a bug in the next.js example. The bug is that the new types that are generated by `graphql-let` as part of the next-js hot reload action seem to be ignored by the typechecker.

### Reproduction steps
1. `npm run dev`
2. Make a change to the schema (e.g. Add a field `isActive: Boolean` to the [User type in the schema](https://github.com/zeit/next.js/blob/canary/examples/with-typescript-graphql/lib/type-defs.graphqls#L4)). Save the file.
3. Add this new field to the [Viewer query](https://github.com/zeit/next.js/blob/canary/examples/with-typescript-graphql/lib/viewer.graphql). Save the file.
4. Add a reference to this new field after the query hook on [the index view](https://github.com/zeit/next.js/blob/canary/examples/with-typescript-graphql/pages/index.tsx). Save the file.
e.g.:
```js
import withApollo from '../lib/with-apollo'
import Link from 'next/link'
import { useViewerQuery } from '../lib/viewer.graphql'

const Index = () => {
  const { data } = useViewerQuery()

  if (data && data.viewer && data.viewer.isActive) {
    const { viewer } = data
    return (
      <div>
        You're signed in as {viewer.name} and you're {viewer.status} goto{' '}
        <Link href="/about">
          <a>static</a>
        </Link>{' '}
        page.
      </div>
    )
  }

  return <div>...</div>
}

export default withApollo(Index)
```
5. In a browser, navigate to `localhost:3000`
### Actual Behavior
New types are ignored: type error reported according to the types initially generated at app start:
![graphql-let-bug](https://user-images.githubusercontent.com/7927187/75688593-faa3b200-5c5c-11ea-83b8-41055e632c76.jpg)
Killing the next.js process and starting it again seems to provide the correct types until another change to the schema occurs i.e. it seems that this bug only occurs during the next.js hot reload action.
### Expected Behavior
During the next.js hot reload action, `graphql-let` properly replaces the generated types with the latest and this is reflected properly by the typechecker.

**Comment by piglovesyou** [comment]
Thank you for using it and raise an issue with clear instruction to reproduce. No time in the week days but I'll definitely dig into it. Let me check a few things.

* What the `viewer.graphql-{hash}.d.ts` definition says? It seems that graphql-let generates a new one. Does it have a field `isActive` or still old?
* I published improvements for HMR in 0.8.x and 0.9.x. What's the version? Could be better if it's older version.
* Not sure it's related but I have to say I forgot to add `graphql-let/schema/loader` in the latest Next.js example. Could you add it to `next.config.js` according to [the doc](https://github.com/piglovesyou/graphql-let#experimental-feature-resolver-types)?

**Comment by deanslamajr** [comment]
* I'm seeing the `d.ts` files in `__generated__/types` are never deleted but instead the number of files increases with each change of either a `*.graphqls` or `*.graphql` file:
![graphql-let-bug2](https://user-images.githubusercontent.com/7927187/75749814-f4a2e500-5cdf-11ea-9737-507fb21fbfab.jpg)
![graphql-let-bug3](https://user-images.githubusercontent.com/7927187/75749847-084e4b80-5ce0-11ea-9e96-1b91926a92a0.jpg)

* `graphql-let@0.9.0`
* I have made this change but I see the same behavior
* Ubuntu 18.04.3 LTS / node.js v12.16.0

**Comment by piglovesyou** [comment]
I appreciate the detailed information. It definitely fails to remove older artifacts. [I'm testing it](https://github.com/piglovesyou/graphql-let/blob/1ed1a313ac041e2c6f8a0d971de3ba39a227b4d5/test/hmr.test.ts#L48-L52) but there seem some cases I don't assume.

Honestly saying, I need time to start working on this issue. If you would happen to help me, I'd like you to check [why here doesn't remove old files](https://github.com/piglovesyou/graphql-let/blob/9a253ffd06d1d042c75a04fefeb26e2086880a05/src/loader.ts#L62) as expected.

Again, raising an issue is enough helping me, thank you😄

**Comment by deanslamajr** [comment]
I think I've found the cause of this bug:

The major version of `globby` is not "locked" in [package.json](https://github.com/piglovesyou/graphql-let/blob/master/package.json#L21). Consequently, if another package has a dependency on a major version of `globby` that is too old for `graphql-let`,  `graphql-let` will use the incorrect version and function incorrectly.

To verify this, there are two different paths to initialize the the next.js example. The first will install a major version of `globby` (`globby@11.0.0`) that supports `graphql-let` correct functionality:
```
npm init next-app --example with-typescript-graphql with-typescript-graphql-app
```
The second path will install a much older major version of `globby` (`globby@^6.1.0`) that seems to break `graphql-let`'s [stale asset removal](https://github.com/piglovesyou/graphql-let/blob/master/src/lib/file.ts#L13):
```
git@github.com:zeit/next.js.git
cd next.js/examples/with-typescript-graphql
npm i
```

I was able to verify that by locking the major version of `globby` to the latest major version (`11.0.0`), this bug can be avoided. I have created a [PR](https://github.com/piglovesyou/graphql-let/pull/68) to implement this change.

**Comment by piglovesyou** [comment]
@deanslamajr Amazing work. I put `"*"` without consideration, perhaps I might have thought it would respect other deps's `globby` and would save a number of total deps or something. I really appreciate your deep investigation and the PR, and `slash` too, which may make another issue in the future. 

Let me close this issue now thanks to your PR. Please let me know if you notice something about graphql-let in your project.

**Comment by piglovesyou** [comment]
Please use `0.9.3` that includes your fix.
