### ISSUE TITLE
Apollo refetchQueries integration?

### ISSUE THREAD

**Issue by james-ff** [piglovesyou/graphql-let#66]
How might this library's generated code plug into Apollo's refetchQueries?

https://www.apollographql.com/docs/react/data/mutations/#options

**Comment by piglovesyou** [comment]
@james-ff Hi. Query document exports DocumentNode named `${QueryName}Document` that you can make use of it.

```typescript jsx
import { ViewerDocument } from '../lib/viewer.graphql'
import { useBlaaMutation } from '../lib/blaa.graphql'

function BlaaButton() {
  const [blaa] = useBlaaMutation({
    refetchQueries: [{ query: ViewerDocument }]
  });

  return <button onClick={() => blaa()}>blaa.</button>
}
```

Glad to hear if it's okay.

**Comment by james-ff** [comment]
Works! Many Thanks

**Comment by piglovesyou** [comment]
Good to hear that!
