### ISSUE TITLE
Fail to generated .d.ts when I add a Mutation

### ISSUE THREAD

**Issue by tscharke** [piglovesyou/graphql-let#73]
Hello,

I am starting with NextJs and use this Repository [with-typescript-graphql](https://github.com/zeit/next.js/tree/canary/examples/with-typescript-graphql) as my basis.

Everything works fine and I can start my dev-server and create a build by running: `graphql-let && next`.

If I add a `mutation` like this…

```
mutation login($username: String!, $password: String!) {
  login(username: $username, password: $password) {
    token
    user {
      id
      username
      email
    }
  }
}
```

and try to use the created Hook `useLoginMutation` inside my login page, the dev-server runs fine again. But a `graphql-let && next build && next start` throws this error:

```
$ graphql-let
[ graphql-let ] .d.ts were generated in __generated__/types.
Creating an optimized production build  

Compiled successfully.

Automatically optimizing pages ...
Error occurred prerendering page "/login". Read more: https://err.sh/next.js/prerender-error:
Invariant Violation: Invariant Violation: 2 (see https://github.com/apollographql/invariant-packages)

> Build error occurred
```

What's going wrong? How can I see more details? Is there a verbose-mode? Can the error be in my mutation or in the code-part using the Hook

It would be super nice if everyone can support me and/or give me some tips 🙏

**Comment by tscharke** [comment]
Interesting 🤔If I do not use/call the Hook inside my page, it builts all correctly and the server starts.

Here is how I use the generated Hook `useLoginMutation` inside my page:

```
const [loginMutation] = useLoginMutation()
…
loginMutation({
  variables: {
    username: 'my username',
    password: 'password',
  },
})
…
```

**Comment by tscharke** [comment]
I'm not sure if it's a workaround or the solution🤷‍♂️

I figured out that everything works as expected if I extract/switch the Components, who uses Hooks like `useLoginMutation`, `useXXXQuery`, out of the `page`'s-folder into a separated folder (e.g. `components`).

**Comment by piglovesyou** [comment]
@tscharke Hi. I appreciate your taking the time to report the issue. Hmm, switching components to use hooks functions reminds me of nothing. Once I realized Next.js doesn't accept GraphQL documents in `pages` directory so I put it in `lib` directory.

Would you push a reproducing repository, if you have time? Thank you.

**Comment by tscharke** [comment]
Thanks come up to me @piglovesyou 🙏

> Once I realized Next.js doesn't accept GraphQL documents in pages directory so I put it in lib directory

It sounds we're meaning the same thing 🤷‍♂️

If you're are using GraphQL-Hooks inside documents in `pages` and calling `graphql-let && next build && next start`, it throws my reported error. If you're using the GraphQL-Hooks outside documents in pages, e.g. inside different folders like `components` in my case and `lib` in your case, everything works fine 😎

**Comment by piglovesyou** [comment]
I meant putting `a.graphql` file in `pages` directory used to give erros. Using react-apollo hooks should work, as the with-typescript-graphql example initially does. Hmm, mutation should equally work as query. I may be able to check if there's a reproducting repo.
