### ISSUE TITLE
Consequences of turning on skipLibCheck?

### ISSUE THREAD

**Issue by aarnej** [piglovesyou/graphql-let#83]
It seems that quite significant performance improvements can be had by turning on the skipLibCheck option here:
https://github.com/piglovesyou/graphql-let/blob/704f98effe7cef09f2c9d6c3615cc78acf3c49ff/src/lib/dts.ts#L9

In our case, a clean run of "yarn graphql-let" improved from 25 seconds to 10 seconds.

In your opinion, what would the consequences of this be in practice?

**Comment by piglovesyou** [comment]
Hi @aarnej , thank you for creating the issue.

**Comment by piglovesyou** [comment]
Seems no problem and 3x faster 😄 I'll merge it.
![Screen Shot 2020-04-28 at 17 26 32](https://user-images.githubusercontent.com/217530/80466393-75e0c600-8977-11ea-859e-184f1074b686.png)

**Comment by aarnej** [comment]
Thanks for the swift response and for the package itself! 

I don't claim to fully understand this setting (even after reading [this](https://stackoverflow.com/questions/52311779/usage-of-the-typescript-compiler-argument-skiplibcheck)) but I imagine it might be useful to somehow check the types of dependencies during installation. Different versions of dependencies might have compatibility issues, which the Typescript compiler might reveal. But I suppose this kind of check would not be necessary on every run at least. 

I don't know if packages generally do something like this.

**Comment by piglovesyou** [comment]
I checked both results were identical. I believe `skipLibCheck: true` is not necessary too. I just didn't have time to optimize the TS option in the initial implementation😃
