### ISSUE TITLE
Cannot read property 'definitions' of undefined

### ISSUE THREAD

**Issue by hjaimee** [piglovesyou/graphql-let#94]
When trying to use my schema definitions of a remote server getting this error

`
[ graphql-let ] Cannot read property 'definitions' of undefined
`

I believe this is from graphql-code-generator as I used this separately and was getting the same issue but upgraded to version 1.13.2 and this seems to have solved it for me in graphql-code-generator.

It seems graphql-let is still using ^1.12.2 which seems to have the problem. 

https://github.com/dotansimha/graphql-code-generator/issues/3445

**Comment by piglovesyou** [comment]
Thank you for taking the time to create this issue. I'm glad to know @graphql-codegen/typescript-react-apollo@1.12.2 breaks URL schema, but actually graphql-let doesn't force you that version. graphql-let has a peer-dependency of @graphql-codegen/cli@^1.12.2, which includes 1.13.2, and updating it is up to users.
