### ISSUE TITLE
Migrating to Apollo Client 3.0 issue

### ISSUE THREAD

**Issue by FlyOrDie** [piglovesyou/graphql-let#95]
Good day!

According to the migration guide of [apollo-client](https://www.apollographql.com/docs/react/v3.0-beta/migrating/apollo-client-3-migration/), react hooks were taken from a separate package to the client itself. So, it causes module_not_found issues. 

./node_modules/@apollo/react-components/node_modules/@apollo/react-hooks/lib/react-hooks.esm.js
Module not found: Can't resolve 'apollo-client' in '/------/node_modules/@apollo/react-components/node_modules/@apollo/react-hooks/lib'

Looks like the generator generates code which requires @apollo/react-hooks package, and this package itself requires apollo-client, which also changes name in version 3 to @apollo/client

**Comment by piglovesyou** [comment]
Hi, thanks for reporting! I'll definitely try to fix that soon, maybe in this weekends.

**Comment by piglovesyou** [comment]
Technically, graphql-let doesn't depend on apollo-client, but @graphql-codegen/typescript-react-apollo does. I think there's nothing we can do except waiting for @graphql-codegen/typescript-react-apollo to support @apollo/client@3.

After that, I'll update the `yarn add` part of README.md.

**Comment by FlyOrDie** [comment]
Thank you very much :) Lets w8 for it :)

**Comment by krijoh92** [comment]
@FlyOrDie If you still want to use @apollo/client@3 and are using babel, you can add (babel-plugin-module-resolver)[https://www.npmjs.com/package/babel-plugin-module-resolver] and add this in your babel configuration in plugins:

```
[
  "module-resolver",
  {
    "alias": {
      "@apollo/react-hooks": "@apollo/client",
    }
  }
]
```

**Comment by thomasdashney** [comment]
Looks like this is now supported in `@graphql-codegen/typescript-react-apollo` using a `version: 3` config flag: https://graphql-code-generator.com/docs/plugins/typescript-react-apollo
