### ISSUE TITLE
Support for graphql string literal

### ISSUE THREAD

**Issue by pranaypratyush** [piglovesyou/graphql-let#98]
I want to be able to use the use gql tag template literal with fragment embedding as I find that format to be easier to read and write. I am not sure how separate `.graphql` files are technically different to string literal format. Is it that it adds a package to parse the query to AST at runtime? If that is true then can we integrate a static compiler that does that for me during build-time? 
https://github.com/firede/ts-transform-graphql-tag

**Comment by piglovesyou** [comment]
Hi! Yeah, that's [the one I wrote in the FAQ](https://github.com/piglovesyou/graphql-let#can-i-write-graphql-documents-in-my-tsx-as-const-query--gqlquery-news--), the tough one. I'd like to ask you, how can we statically type the return value? I have one ugly idea actually, but I'd like to hear your idea first🙂

**Comment by pranaypratyush** [comment]
Do you mean how to type using AST? 
Also, why did we lose the `graphql-tag-pluck` that's there in codegen?

**Comment by pranaypratyush** [comment]
I get it now it seems. Next.js uses babel for typescript. I had ignored this crucial part. So we are stuck with `babel-loader`.

**Comment by piglovesyou** [comment]
Because we're in TypeScript world🙂

So, graphql-let does 2 things:

* Running graphql-codegen under the hood
* **Type the result**

So when you use graphql-let:

```typescript
import { useAQuery } from './a.graphql'
```

The `useAQuery` is not only callable, its arguments and return type is also available for your type checker.

And we also want to write it like this:

```typescript
const { useAQuery } = gql`query A { a }`;
```

But here's a problem. How can we type `useAQuery`? Since it's in a file, it's hard to insert type definition for the `useAQuery` function.

**Comment by pranaypratyush** [comment]
Can we do `declare var useAQuery : useAQueryInterface` in a `.d.ts` file? 

And while we are at it, https://github.com/gajus/babel-plugin-graphql-tag  would give us the AST at build time and we plug that into your code.

**Comment by piglovesyou** [comment]
Mmm, how can we apply the? More specific example would be nice.

And yes, running graphql-codegen is possible at build time, as you know. Problem is how to type.

**Comment by piglovesyou** [comment]
Current status: [I tried my idea, but no luck](https://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=19&pc=19#code/C4TwDgpgBAggTgIwJbDgQziAShYBXOAOwBVxoBeKAdgA4BOAbgFgAoVgMz0IGNgkB7QlADmARwA2ACgAeALig40AE0HiQAHgDaAclF4ImWFADeaAL7aAugD4AlPPjJUGbLgIkyzFpx59BIiRl5YggAWzBxNGAIAGVUJEJhAGd4dBB7KCT4xK8fXgEhMSk5KDRCdPkykBMoODciKGlSpNLyhigzVlYAem6oAFFpSF4IJShgfigEaCS8bm4IUdGAGim8YChCSfE5gGtWIoADPQNqmBNzQ+bYRBR0TBx8IlJILx6+gHl9liO0K7QWlk4AlhF4gA). I thought overloading over TaggedTemplate function could type arbitrary query call like `` gql`query A {a}` `` , but it didn't work. Hmm. I think there's no solution to type return value of a TaggedTemplate call, dynamically.

**Comment by pranaypratyush** [comment]
Take a look at their approach. https://github.com/PabloSzx/graphql-tag-ts

**Comment by pranaypratyush** [comment]
```
declare module "graphql-tag" {
    export default function gql(x: TemplateStringsArray): ArbitraryReturnType
}
``` 
What about this?

**Comment by pranaypratyush** [comment]
A simple solution would be to make the user write `gql<typeA,typeV>` instead, and define typeA and typeV through autogeneration. `graphql-tag-ts` would do the rest.

**Comment by piglovesyou** [comment]
That's not a too bad idea. Cons:

* Users have to import these types. They still have to import something after all
* What's the filename to be imported going to be?/ Do users know it easily?
* What's the difference from graphql-codegen? Isn't that something the same/worse?

I still can't draw the final design🧐

**Comment by pranaypratyush** [comment]
Fair point. That's a no go I think. 
Possible options: 
1. What if we inject the types along with `import gql from 'graphql-tag'` line using babel-loader. Is this possible? 
2. If not then we create an alias package `graphql-typed-tag`, one that we control and injects the types. 
3. Full-fledged Babel plugin that injects the type imports appropriately. 
4. All we need is the editor to pick up the types. If users actually care about linting through official typescript they would go through the trouble of generating and importing proper type every time. So might as well just have an editor plugin

**Comment by piglovesyou** [comment]
I pushed **graphql-let@canary**, containing Babel Plugin support allowing you to get typed graphql-codegen results from inline GraphQL documents. Please drop a comment before merging it if you notice something.

https://github.com/piglovesyou/graphql-let/tree/pr-gql-tag#experimental-feature-babel-plugin-for-inline-graphql-documents

**Comment by pranaypratyush** [comment]
Will do sir. Gonna use it in a new project I am heading. Thanks for your work.
